name: Build and Deploy Docker Image

on:
  push:
    branches:
      - master  # Пайплайн срабатывает при пуше в основную ветку

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}  # Логин Docker Hub
          password: ${{ secrets.DOCKER_PASSWORD }}  # Пароль Docker Hub

      - name: Build Docker image
        run: |
          docker build -t inspiredx/telegram-gobot:alpine .

      - name: Push Docker image to Docker Hub
        run: |
          docker push inspiredx/telegram-gobot:alpine

  deploy:
    runs-on: ubuntu-latest
    needs: build  # Ждем завершения стадии build
    steps:
      - name: Deploy to server
        run: |
          ssh -o StrictHostKeyChecking=no root@154.59.110.208 "
            docker pull inspiredx/telegram-gobot:alpine &&
            docker stop telegram-gobot || true &&
            docker rm telegram-gobot || true &&
            docker run -d --name telegram-gobot inspiredx/telegram-gobot:alpine
          "
